language: node_js

node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test
  - yarn build

before_deploy:
  - ls
  - ls | grep -v "`cat Deploylist`" | xargs rm -r
  - rm .babelrc .editorconfig .eslintrc.js .gitignore
  - wget https://raw.githubusercontent.com/SB-IM/SDWC/gh-pages/config.json
  - ls -a


deploy:
  provider: pages
  fqdn: test.newbe.cc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: dev

